// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using PropertyPlatform.Infrastructure.Data;

#nullable disable

namespace PropertyPlatform.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("PropertyPlatform.Core.Entities.AgentBadge", b =>
                {
                    b.Property<Guid>("AgentBadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("AwardedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("BadgeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("AgentBadgeId");

                    b.HasIndex("BadgeId");

                    b.HasIndex("TenantId");

                    b.ToTable("AgentBadges");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.AgentMission", b =>
                {
                    b.Property<Guid>("AgentMissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("CurrentProgress")
                        .HasColumnType("integer");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("boolean");

                    b.Property<Guid>("MissionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("AgentMissionId");

                    b.HasIndex("MissionId");

                    b.HasIndex("TenantId");

                    b.ToTable("AgentMissions");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.AgentProfile", b =>
                {
                    b.Property<Guid>("AgentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Bio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CompanyLogoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Credits")
                        .HasColumnType("integer");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ExperiencePoints")
                        .HasColumnType("integer");

                    b.Property<int>("Level")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("OfficeAddress")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProfilePhotoUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("REN_ID")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("AgentId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("TenantId")
                        .IsUnique();

                    b.ToTable("AgentProfiles");

                    b.HasData(
                        new
                        {
                            AgentId = new Guid("00000000-0000-0000-0000-000000000101"),
                            Bio = "System Administrator",
                            CompanyLogoUrl = "https://via.placeholder.com/150",
                            Credits = 0,
                            Email = "admin",
                            ExperiencePoints = 0,
                            Level = 1,
                            Name = "Platform Admin",
                            OfficeAddress = "System HQ",
                            PasswordHash = "$2a$11$pxNvtTsemAwY0LSFV3JE6.k2WEG1OzVBkbMHIOs3rsQmUDrTV2.r.",
                            Phone = "000-000-0000",
                            ProfilePhotoUrl = "https://via.placeholder.com/150",
                            REN_ID = "ADMIN-001",
                            Slug = "admin",
                            TenantId = new Guid("00000000-0000-0000-0000-000000000100")
                        });
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.AgentReview", b =>
                {
                    b.Property<Guid>("ReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentTenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsVerified")
                        .HasColumnType("boolean");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("ReviewerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ReviewerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("ReviewId");

                    b.HasIndex("AgentTenantId");

                    b.ToTable("AgentReviews");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.Article", b =>
                {
                    b.Property<Guid>("ArticleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("PublishedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("ThumbnailUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ArticleId");

                    b.HasIndex("Category");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            ArticleId = new Guid("00000000-0000-0000-0000-000000000301"),
                            Author = "System Admin",
                            Category = "Company News",
                            Content = "<p>Welcome to the <strong>Annie Rustic Property Platform</strong>. We have completely rewritten our core engine to provide a seamless, AI-powered experience for agents and buyers alike.</p><p>Explore our new features including AI-driven listing automation, smart lead management, and premium agent microsites.</p>",
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "We are excited to announce the launch of our next-generation property ecosystem.",
                            PublishedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "welcome-to-new-platform",
                            Status = "Published",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?auto=format&fit=crop&q=80&w=800",
                            Title = "Welcome to the New Property Platform",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            ArticleId = new Guid("00000000-0000-0000-0000-000000000302"),
                            Author = "Market Analytics Team",
                            Category = "Market Trends",
                            Content = "<p>The residential market in early 2026 shows a strong preference for mixed-use developments and smart home integrations.</p><p>Our data indicates a 15% increase in searches for properties with dedicated home office spaces and high-speed fiber connectivity.</p>",
                            CreatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Excerpt = "Analyzing the shift in urban living preferences and price stability in major metropolitan areas.",
                            PublishedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            Slug = "market-trends-q1-2026",
                            Status = "Published",
                            ThumbnailUrl = "https://images.unsplash.com/photo-1460472178825-e52506b3f90a?auto=format&fit=crop&q=80&w=800",
                            Title = "Market Trends: Q1 2026 Residential Outlook",
                            UpdatedAt = new DateTime(2026, 2, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.Badge", b =>
                {
                    b.Property<Guid>("BadgeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("BadgeId");

                    b.ToTable("Badges");

                    b.HasData(
                        new
                        {
                            BadgeId = new Guid("00000000-0000-0000-0000-000000000001"),
                            Code = "RISING_STAR",
                            Description = "Joined the platform and completed initial setup.",
                            IconUrl = "✨",
                            Name = "Rising Star"
                        },
                        new
                        {
                            BadgeId = new Guid("00000000-0000-0000-0000-000000000002"),
                            Code = "ELITE_LISTER",
                            Description = "Uploaded 10 high-quality listings.",
                            IconUrl = "🏆",
                            Name = "Elite Lister"
                        });
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.CreditTransaction", b =>
                {
                    b.Property<Guid>("TransactionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Amount")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TransactionId");

                    b.HasIndex("TenantId");

                    b.ToTable("CreditTransactions");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.FeatureConfig", b =>
                {
                    b.Property<Guid>("FeatureConfigId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FeatureKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FeatureConfigId");

                    b.ToTable("FeatureConfigs");

                    b.HasData(
                        new
                        {
                            FeatureConfigId = new Guid("00000000-0000-0000-0000-000000000201"),
                            Category = "ListingType",
                            Description = "Allow agents to create listings for property sales.",
                            DisplayName = "Property Sale",
                            FeatureKey = "sale",
                            IsEnabled = true,
                            SortOrder = 1,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FeatureConfigId = new Guid("00000000-0000-0000-0000-000000000202"),
                            Category = "ListingType",
                            Description = "Allow agents to create listings for residential or commercial rentals.",
                            DisplayName = "Property Rental",
                            FeatureKey = "rent",
                            IsEnabled = true,
                            SortOrder = 2,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        },
                        new
                        {
                            FeatureConfigId = new Guid("00000000-0000-0000-0000-000000000203"),
                            Category = "ListingType",
                            Description = "Allow agents to create listings for new developer projects.",
                            DisplayName = "New Projects",
                            FeatureKey = "new-project",
                            IsEnabled = true,
                            SortOrder = 3,
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.FeaturedListing", b =>
                {
                    b.Property<Guid>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("BoostLevel")
                        .HasColumnType("integer");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("FeatureId");

                    b.HasIndex("ListingId")
                        .IsUnique();

                    b.ToTable("FeaturedListings");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.FloorPlan", b =>
                {
                    b.Property<Guid>("FloorPlanId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.HasKey("FloorPlanId");

                    b.HasIndex("ListingId");

                    b.ToTable("FloorPlans");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.Lead", b =>
                {
                    b.Property<Guid>("LeadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("BuyerEmail")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuyerName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("BuyerPhone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContactType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("LeadId");

                    b.HasIndex("ListingId");

                    b.HasIndex("TenantId");

                    b.ToTable("Leads");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.ListingAnalytic", b =>
                {
                    b.Property<Guid>("AnalyticsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Clicks")
                        .HasColumnType("integer");

                    b.Property<int>("Contacts")
                        .HasColumnType("integer");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Views")
                        .HasColumnType("integer");

                    b.HasKey("AnalyticsId");

                    b.HasIndex("ListingId")
                        .IsUnique();

                    b.ToTable("ListingAnalytics");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.Mission", b =>
                {
                    b.Property<Guid>("MissionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("CreditReward")
                        .HasColumnType("integer");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("RequirementCount")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("XPReward")
                        .HasColumnType("integer");

                    b.HasKey("MissionId");

                    b.ToTable("Missions");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.PropertyFeature", b =>
                {
                    b.Property<Guid>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("FeatureId");

                    b.HasIndex("ListingId");

                    b.ToTable("PropertyFeatures");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.PropertyListing", b =>
                {
                    b.Property<Guid>("ListingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ListingType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.Property<string>("PropertyType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("ListingId");

                    b.HasIndex("ListingType");

                    b.HasIndex("Location");

                    b.HasIndex("TenantId");

                    b.ToTable("PropertyListings");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.PropertyMedia", b =>
                {
                    b.Property<Guid>("MediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<string>("MediaType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MediaUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer");

                    b.HasKey("MediaId");

                    b.HasIndex("ListingId");

                    b.ToTable("PropertyMedia");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.Referral", b =>
                {
                    b.Property<Guid>("ReferralId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("NewTenantId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ReferrerTenantId")
                        .HasColumnType("uuid");

                    b.HasKey("ReferralId");

                    b.HasIndex("NewTenantId");

                    b.HasIndex("ReferrerTenantId");

                    b.ToTable("Referrals");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.RefreshToken", b =>
                {
                    b.Property<Guid>("TokenId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("ExpiryDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("boolean");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("TokenId");

                    b.HasIndex("TenantId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.Subscription", b =>
                {
                    b.Property<Guid>("SubscriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Plan")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid");

                    b.HasKey("SubscriptionId");

                    b.HasIndex("TenantId");

                    b.ToTable("Subscriptions");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.Tenant", b =>
                {
                    b.Property<Guid>("TenantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("ContactEmail")
                        .HasColumnType("text");

                    b.Property<string>("ContactPhone")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("LogoUrl")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PostalCode")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TenantId");

                    b.ToTable("Tenants");

                    b.HasData(
                        new
                        {
                            TenantId = new Guid("00000000-0000-0000-0000-000000000100"),
                            CreatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            IsActive = true,
                            Name = "Platform Administration",
                            UpdatedAt = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc)
                        });
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.UserEvent", b =>
                {
                    b.Property<Guid>("EventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("EventId");

                    b.HasIndex("ListingId");

                    b.ToTable("UserEvents");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.AgentBadge", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.Badge", "Badge")
                        .WithMany()
                        .HasForeignKey("BadgeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyPlatform.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Badge");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.AgentMission", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.Mission", "Mission")
                        .WithMany()
                        .HasForeignKey("MissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyPlatform.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Mission");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.AgentProfile", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.Tenant", "Tenant")
                        .WithOne("AgentProfile")
                        .HasForeignKey("PropertyPlatform.Core.Entities.AgentProfile", "TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.AgentReview", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.Tenant", "AgentTenant")
                        .WithMany()
                        .HasForeignKey("AgentTenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("AgentTenant");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.CreditTransaction", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.Tenant", "Tenant")
                        .WithMany("CreditTransactions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.FeaturedListing", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.PropertyListing", "Listing")
                        .WithOne("FeaturedListing")
                        .HasForeignKey("PropertyPlatform.Core.Entities.FeaturedListing", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.FloorPlan", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.PropertyListing", "Listing")
                        .WithMany("FloorPlans")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.Lead", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.PropertyListing", "Listing")
                        .WithMany("Leads")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("PropertyPlatform.Core.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.ListingAnalytic", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.PropertyListing", "Listing")
                        .WithOne("Analytics")
                        .HasForeignKey("PropertyPlatform.Core.Entities.ListingAnalytic", "ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.PropertyFeature", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.PropertyListing", "Listing")
                        .WithMany("Features")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.PropertyListing", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.Tenant", "Tenant")
                        .WithMany("PropertyListings")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.PropertyMedia", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.PropertyListing", "Listing")
                        .WithMany("Media")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.Referral", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.Tenant", "NewTenant")
                        .WithMany("ReferralsReceived")
                        .HasForeignKey("NewTenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("PropertyPlatform.Core.Entities.Tenant", "Referrer")
                        .WithMany("ReferralsMade")
                        .HasForeignKey("ReferrerTenantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("NewTenant");

                    b.Navigation("Referrer");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.RefreshToken", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.Tenant", "Tenant")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.Subscription", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.Tenant", "Tenant")
                        .WithMany("Subscriptions")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.UserEvent", b =>
                {
                    b.HasOne("PropertyPlatform.Core.Entities.PropertyListing", "Listing")
                        .WithMany("UserEvents")
                        .HasForeignKey("ListingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Listing");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.PropertyListing", b =>
                {
                    b.Navigation("Analytics");

                    b.Navigation("FeaturedListing");

                    b.Navigation("Features");

                    b.Navigation("FloorPlans");

                    b.Navigation("Leads");

                    b.Navigation("Media");

                    b.Navigation("UserEvents");
                });

            modelBuilder.Entity("PropertyPlatform.Core.Entities.Tenant", b =>
                {
                    b.Navigation("AgentProfile");

                    b.Navigation("CreditTransactions");

                    b.Navigation("PropertyListings");

                    b.Navigation("ReferralsMade");

                    b.Navigation("ReferralsReceived");

                    b.Navigation("RefreshTokens");

                    b.Navigation("Subscriptions");
                });
#pragma warning restore 612, 618
        }
    }
}
